image: maven:3.8-openjdk-11

default:
  tags:
    - shelllocal

stages:
  - test

Regression test:
  stage: test
  script:
    - mvn clean test -DsuiteXmlFile="src/test/resources/testng.xml"
  after_script:
    - mvn allure:report
  artifacts:
    when: always
    paths:
      - target/site/allure-maven-plugin/*