image: maven:3.8-openjdk-11

default:
  tags:
    - shelllocal

stages:
  - test

Regression test with Allure:
  stage: test
  script:
    - mvn clean test -DsuiteXmlFile="src/test/resources/testng.xml"
    - mvn allure:report
  artifacts:
    paths:
      - target/site/allure-maven-plugin/*