image: maven:3.8-openjdk-11

default:
  tags:
    - shelllocal

stages:
  - Runnig tests
  - Generate allure report

Runnig tests:
  stage: Runnig tests
  script:
    - mvn clean test -DsuiteXmlFile="src/test/resources/testng.xml"

Generate allure report:
  stage: Generate allure report
  script:
    - mvn allure:report
  artifacts:
    when: always
    paths:
      - target/site/allure-maven-plugin/